[build]
rustflags = [
"-C", "force-unwind-tables=yes", # backtrace on panic doen't work in debug mode without this (but works in release for some reason)
"-C", "force-frame-pointers=yes", # make profilers work slightly better, maybe
]
